ryanrosello-og/playwright-slack-report

- package.json
- src/SlackClient.ts
- src/SlackReporter.ts
Add extra logging in order to troubleshoot https://github.com/ryanrosello-og/playwright-slack-report/issues/8
> add extra logs

- README.md
> [Docs] Fix wrong documentation examples

- package.json
- src/SlackReporter.ts
Fix for https://github.com/ryanrosello-og/playwright-slack-report/issues/27
> Fix slack auth token config key

- .github/workflows/playwright.yml
- README.md
- package.json
- src/SlackReporter.ts
- yarn.lock
Fixes for the following:
- https://github.com/ryanrosello-og/playwright-slack-report/issues/36
- https://github.com/ryanrosello-og/playwright-slack-report/issues/44
- https://github.com/ryanrosello-og/playwright-slack-report/issues/43
> Fix gh issues

- README.md
- package.json
- src/SlackReporter.ts
- yarn.lock
Add a new setting which allows you to specify a proxy server to route your Slack message requests.
> add option for proxy config

- .eslintrc.json
- README.md
- package.json
- src/ResultsParser.ts
- src/SlackReporter.ts
- src/SlackWebhookClient.ts
- tests/SlackReporter.spec.ts
- tests/SlackWehookClient.spec.ts
- yarn.lock
Added an extra configuration to allow messages to be sent via webhook
> Add option to send message via webhooks

- package.json
- src/LayoutGenerator.ts
- src/SlackReporter.ts
- src/custom_block/my_block.ts
- tests/SlackClient_generate_blocks.spec.ts
Fixed GH issue => https://github.com/ryanrosello-og/playwright-slack-report/issues/51
Fixed incorrect message shown when `maxNumberOfFailuresToShow` is enabled.
> Fix multi channel thread && broken maxFailures logic

- README.md
- package-lock.json
- src/LayoutGenerator.ts
- src/ResultsParser.ts
- src/SlackReporter.ts
- src/SlackWebhookClient.ts
- src/index.ts
- tests/ResultsParser.spec.ts
- tests/SlackClient_generate_blocks.spec.ts
- tests/SlackWehookClient.spec.ts
- tests/fixtures.ts
- yarn.lock
Conditionally enabled by config option `separateFlaky` of type boolean. Default is false, which will not change the current behaviour.
> separate flaky tests from output - passes that did not pass on first try are instead output as flaky, not passed

- src/LayoutGenerator.ts
- src/SlackClient.ts
Fix for https://github.com/ryanrosello-og/playwright-slack-report/issues/59
> add fallback text

- package.json
- src/SlackReporter.ts
Fix for https://github.com/ryanrosello-og/playwright-slack-report/issues/90
> Fix issue with unable to send using webhook option

- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/close_stale_issues.yml
Added actions:
* Close stale issues/PR template
* Enabled dependabot
* Added PR template
> various gh actions

- package.json
chore - version bump to 1.1.80
> version bump for release

- custom_block/cli_block_with_meta.ts
- package.json
- src/ResultsParser.ts
- src/SlackClient.ts
- tests/ResultsParser.spec.ts
- yarn.lock
Fix https://github.com/ryanrosello-og/playwright-slack-report/issues/155
> fix issue with expected failures not appearing

- README.md
- src/SlackReporter.ts
Reverts ryanrosello-og/playwright-slack-report#162
> Revert "Add slackWebHookChannel Option for Multiple Slack Channels"

- src/ResultsParser.ts
Adjust changes from #166 to allow inclusion of each test once _per project_. 
Only the comment [here](https://github.com/ryanrosello-og/playwright-slack-report/pull/166/files#r1730423813)
> Report per project failing tests

- .github/workflows/playwright.yml
* update upload-artifact gh action
Describe your changes.
Add link to the related issue.
> Chore/update upload artifact action (#189)

- .github/workflows/close_stale_issues.yml
- .github/workflows/playwright.yml
- .github/workflows/publish.yml
- package.json
> chore: bump version to 1.1.90

- package.json
> chore: bump version to 1.1.93

- package.json
Version bump
Add link to the related issue.
> Bump version to 1.1.94 in package.json

- package.json
Version to for republish GH action step
Add link to the related issue.
> Bump version to 1.1.95 in package.json

- package.json
> Bump version to 1.1.98 in package.json

- package.json
This pull request includes a minor version bump in the `package.json` file, updating the package version from `1.1.98` to `1.1.99`.
Add link to the related issue.
> chore: bump version to 1.1.99
